'use client';

import { CssBaseline, ThemeProvider } from '@mui/material';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { useState } from 'react';
import Header from './components/Header';
import './globals.scss';
import { darkTheme, lightTheme } from './theme/theme';

//const inter = Inter({ subsets: ['latin'] });

/*export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};*/

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const [isDark, setIsDark] = useState(false);
	const switchTeam: any = () => {
		setIsDark(!isDark);
	};

	return (
		<html lang='en'>
			<ThemeProvider theme={isDark ? darkTheme : lightTheme}>
				<LocalizationProvider dateAdapter={AdapterDayjs}>
					<CssBaseline />
					<Header switchTheme={switchTeam} />
					<body>{children}</body>
				</LocalizationProvider>
			</ThemeProvider>
		</html>
	);
}
